In [ ]:
import pandas as pd
import numpy as np

dataset=pd.read_csv('cardio_dataset.csv').values

data=dataset[:,0:7]
target=dataset[:,7]

target=np.reshape(target, (-1,1))

print(data[:10])
print(target[:10])
print('size of the dataset:',len(dataset))

[[  2.  48. 236.  66.   0.   2.   0.]
 [  1.  48. 260.  51.   0.   2.   1.]
 [  1.  44. 187.  49.   1.   2.   0.]
 [  2.  42. 216.  57.   1.   2.   0.]
 [  2.  56. 156.  42.   0.   2.   0.]
 [  1.  44. 162.  57.   1.   2.   0.]
 [  1.  50. 244.  47.   0.   2.   0.]
 [  1.  48. 212.  30.   1.   2.   0.]
 [  2.  66. 202.  53.   0.   2.   1.]
 [  1.  63. 186.  46.   1.   2.   0.]]
[[ 1.1]
 [ 7. ]
 [ 7. ]
 [ 0.4]
 [ 2.2]
 [ 3. ]
 [ 4.2]
 [17.4]
 [13.4]
 [17.3]]
size of the dataset: 6644


In [ ]:
from sklearn.model_selection import train_test_split

train_data,test_data,train_target,test_target=train_test_split(data,target,test_size=0.1)

In [ ]:
from sklearn.linear_model import LinearRegression

model=LinearRegression()

model.fit(train_data,train_target)
predicted_target=model.predict(test_data)

In [ ]:
from sklearn.metrics import r2_score

r2=r2_score(test_target,predicted_target)
print("r2 score:",r2)

r2 score: 0.7582094649564692


In [ ]:
print('Actual Target:',test_target[:10].T)
print('Predicted Target:',predicted_target[:10].T)

Actual Target: [[19.1 14.7 30.9  8.3  2.6  2.4 14.3 14.6  6.6  3.1]]
Predicted Target: [[20.33336949 19.94445968 18.4995706  20.79633703  3.68326182 -0.42903847
  17.12970518 17.3475694   9.54577098  3.98755542]]


In [ ]:
import joblib

joblib.dump(model,'heart_risk_prediction_regression_model.sav')

['heart_risk_prediction_regression_model.sav']